version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: tasktracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: tasktracker
      POSTGRES_PASSWORD: tasktracker_pw
      TZ: Asia/Jakarta
    ports:
      - '5433:5432' # host:container
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tasktracker -d task_tracker']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-data:
